server:
  port: 8700
---
spring:
  application.name: client-bar
  profiles.active: dev
---
endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
  refresh:
    enabled: true
---
management.security.enabled: false